#!/bin/sh
#Build parameters


PARAM_PROJECT_PATH="/home/username/www/drupalcampwroclaw/website_2015"

PARAM_DRUPAL_LOCATION="app"

PARAM_SITE_DIRECTORY=default

PARAM_SITE_URI=www.drupalcampwroclaw.local

PARAM_PROJECT_IS_NEW="no"

PARAM_INSTALLATION_PROFILE="drupalcampwroclaw"

PARAM_SITE_NAME="DrupalCamp Wrocław"

PARAM_ADMIN_NAME="admin"

PARAM_ADMIN_PASS="123"

# For existing project:

PARAM_DBUSER="drupalcamp"
PARAM_DBPASS="drupalcamp"
PARAM_DBNAME_DRUPAL="drupalcamp"
PARAM_DBDUMP_FILE="database.sql.tar.gz"
