<?php
/**
 * @file
 * Code for the Mobile feature.
 */

include_once 'mobileapi.features.inc';

/**
 * Implements hook_service_resources().
 *
 * Sample URL:
 *   http://example.com/api/session_day.json
 */
function mobileapi_services_resources() {

  $resources = array(
    'sessions' => array(
      'operations' => array(
        'index' => array(
          'file' => array(
            'type' => 'inc',
            'module' => 'mobileapi',
            'name' => 'resources/mobileapi',
          ),
          'callback' => 'mobileapi_sessions_services_data',
          'access arguments' => array('access content'),
        ), // end Index
      ),
    ),
  );

  return $resources;
}